apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-webspring
  label:
    app: webspring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webspring
  template:
    metadata:
      labels:
        app: webspring
    spec:
      containers:
      - name: webspring
        image: delcontainer.azurecr.io/webspring2
        ports:
        - containerPort: 8888

---
apiVersion: v1
kind: Service
metadata:
  name: aks-webspring 
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: webspring
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aks-helloworld
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
spec:
  rules:
  - host: aks-helloworld.e9f3ce418c4b450c8428.eastus.aksapp.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service: 
            name: aks-helloworld
            port: 
              number: 80